// Additional encounter hooks generated by the "more hooks" button in the map
// detail pane. Stored per filename because the map-tagger index is read-only;
// we layer these overrides on top of the sidecar-provided hooks at render time.

import { getPf2eDb } from './connection.js';
import { tryParseJson } from './internal.js';

export function getAdditionalHooksFor(fileName: string): string[] {
  const row = getPf2eDb().prepare('SELECT additional_hooks FROM hook_overrides WHERE file_name = ?').get(fileName) as
    | { additional_hooks: string }
    | undefined;
  if (!row) return [];
  const parsed = tryParseJson<unknown>(row.additional_hooks, null);
  return Array.isArray(parsed) ? (parsed as string[]) : [];
}

export function upsertAdditionalHooks(fileName: string, hooks: string[]): void {
  getPf2eDb()
    .prepare(
      `INSERT INTO hook_overrides (file_name, additional_hooks, last_generated_at)
       VALUES (?, ?, ?)
       ON CONFLICT(file_name) DO UPDATE SET
         additional_hooks = excluded.additional_hooks,
         last_generated_at = excluded.last_generated_at`,
    )
    .run(fileName, JSON.stringify(hooks), new Date().toISOString());
}
