// Inline DDL for pf2e.db's app-owned tables (settings, globe pins, inventory,
// combat, aurus teams, hook overrides, pack mappings). The compendium tables
// (monsters, items, npcs) are created by the pre-build pipeline that ships
// with the app — migratePf2eDb only owns tables dm-tool writes to.

import type Database from 'better-sqlite3';

export function migratePf2eDb(db: Database.Database): void {
  db.exec(`
    CREATE TABLE IF NOT EXISTS globe_pins (
      id    TEXT PRIMARY KEY,
      lng   REAL NOT NULL,
      lat   REAL NOT NULL,
      label TEXT NOT NULL DEFAULT '',
      icon  TEXT NOT NULL DEFAULT '',
      zoom  REAL NOT NULL DEFAULT 2
    )
  `);
  // Add columns if migrating from earlier schema.
  const cols = db.prepare("SELECT name FROM pragma_table_info('globe_pins')").all() as { name: string }[];
  const has = (name: string) => cols.some((c) => c.name === name);
  if (!has('icon')) db.exec("ALTER TABLE globe_pins ADD COLUMN icon TEXT NOT NULL DEFAULT ''");
  if (!has('zoom')) db.exec('ALTER TABLE globe_pins ADD COLUMN zoom REAL NOT NULL DEFAULT 2');
  if (!has('note')) db.exec("ALTER TABLE globe_pins ADD COLUMN note TEXT NOT NULL DEFAULT ''");
  if (!has('kind')) db.exec("ALTER TABLE globe_pins ADD COLUMN kind TEXT NOT NULL DEFAULT 'note'");
  // Mirror of the linked Obsidian mission note's markdown, refreshed every
  // time the payload is built for a push. Null for non-mission pins or when
  // no Obsidian vault is configured.
  if (!has('mission_markdown')) db.exec('ALTER TABLE globe_pins ADD COLUMN mission_markdown TEXT');
  if (!has('icon_color')) db.exec("ALTER TABLE globe_pins ADD COLUMN icon_color TEXT NOT NULL DEFAULT ''");

  // Party inventory + Aurus leaderboard — persisted as JSON rows so schema
  // changes stay localized to shared/types.ts. The sidecar is the live-sync
  // authority; SQLite here is the DM's source of truth.
  db.exec(`
    CREATE TABLE IF NOT EXISTS party_inventory (
      id         TEXT PRIMARY KEY,
      data       TEXT NOT NULL,
      updated_at TEXT NOT NULL
    )
  `);
  db.exec(`
    CREATE TABLE IF NOT EXISTS aurus_teams (
      id         TEXT PRIMARY KEY,
      data       TEXT NOT NULL,
      updated_at TEXT NOT NULL
    )
  `);
  db.exec(`
    CREATE TABLE IF NOT EXISTS encounters (
      id         TEXT PRIMARY KEY,
      data       TEXT NOT NULL,
      updated_at TEXT NOT NULL
    )
  `);

  // Additional encounter hooks generated by the "more hooks" button in the
  // detail pane — stored here rather than in the map-tagger index (which
  // we only open read-only). One row per map filename; hooks are a JSON
  // array stored newest-first.
  db.exec(`
    CREATE TABLE IF NOT EXISTS hook_overrides (
      file_name         TEXT PRIMARY KEY,
      additional_hooks  TEXT NOT NULL,
      last_generated_at TEXT NOT NULL
    )
  `);

  // AI-generated pack groupings for map files. Row-per-file; the cached
  // mapping is whatever's in the table. Populated by parseAndCacheMapping
  // (from the Claude paste flow) and touched up by mergePacks.
  db.exec(`
    CREATE TABLE IF NOT EXISTS pack_mappings (
      file_name TEXT PRIMARY KEY,
      pack_name TEXT NOT NULL
    )
  `);

  // Key/value settings that used to live in config.json. Values are JSON-
  // encoded so we can round-trip strings, numbers, booleans, and objects
  // without a schema migration per setting type.
  db.exec(`
    CREATE TABLE IF NOT EXISTS settings (
      key   TEXT PRIMARY KEY,
      value TEXT NOT NULL
    )
  `);

  // Lazy cache of foundry-mcp compendium documents. Populated on demand by
  // the HTTP client in apps/dm-tool/electron/compendium — one row per uuid
  // we've actually fetched. Graceful degradation for brief mcp outages, not
  // a pre-warm. fetched_at is epoch millis; body_json is the serialized
  // CompendiumDocument response.
  db.exec(`
    CREATE TABLE IF NOT EXISTS pf2e_compendium_docs (
      uuid       TEXT PRIMARY KEY,
      fetched_at INTEGER NOT NULL,
      body_json  TEXT NOT NULL
    )
  `);
}
