// Spawns the map-tagger CLI as a child process and streams progress back
// to the renderer via IPC events.
//
// The tagger is a Python CLI tool that expects a config.toml. We generate
// a temporary TOML from dm-tool's unified config.json so there's a single
// source of truth for paths. The API key is passed via the
// ANTHROPIC_API_KEY env var so it never touches disk.

import { spawn, type ChildProcess } from 'node:child_process';
import { writeFileSync, unlinkSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { app } from 'electron';
import type { DmToolConfig } from './config.js';
import { DEFAULT_MODEL } from './constants.js';

export interface TaggerOptions {
  sourcePath: string;
  apiKey: string;
  limit: number;
  concurrency?: number;
  preview?: boolean;
}

export interface TaggerProgress {
  type: 'stdout' | 'stderr';
  line: string;
}

export interface TaggerResult {
  exitCode: number | null;
  signal: string | null;
}

/** Writes a temporary config.toml compatible with the map-tagger CLI.
 *  Returns the absolute path to the file. Caller is responsible for
 *  cleanup via `cleanupTempConfig`. */
function writeTempConfig(cfg: DmToolConfig): string {
  const dir = join(app.getPath('userData'), 'tagger-tmp');
  mkdirSync(dir, { recursive: true });
  const path = join(dir, 'config.toml');

  // All paths are absolute so the anchor-relative resolution in the
  // tagger's config loader is a no-op.
  const toml = `# Auto-generated by dm-tool — do not edit.
[paths]
inbox      = '${cfg.inboxPath.replace(/\\/g, '\\\\')}'
library    = '${cfg.libraryPath.replace(/\\/g, '\\\\')}'
quarantine = '${cfg.quarantinePath.replace(/\\/g, '\\\\')}'
index_db   = '${cfg.indexDbPath.replace(/\\/g, '\\\\')}'

[anthropic]
# API key passed via ANTHROPIC_API_KEY env var, not written to disk.
model = '${DEFAULT_MODEL}'
max_output_tokens = 1500

[eagle]
enabled = false

[tagging]
max_tags = 20
dedup = true

[thumbnails]
enabled = true
max_edge = 512
`;

  writeFileSync(path, toml, 'utf-8');
  return path;
}

function cleanupTempConfig(path: string): void {
  try {
    unlinkSync(path);
  } catch {
    // Best-effort cleanup.
  }
}

let activeProcess: ChildProcess | null = null;

/** Spawn the tagger CLI and stream stdout/stderr lines back via the
 *  `onProgress` callback. Returns a promise that resolves when the
 *  process exits. */
export function runTagger(
  cfg: DmToolConfig,
  opts: TaggerOptions,
  onProgress: (p: TaggerProgress) => void,
): Promise<TaggerResult> {
  if (!cfg.taggerBinPath) {
    throw new Error('Map tagger not configured — set taggerBinPath in config.json or install the bundled binary');
  }
  if (activeProcess) {
    throw new Error('A tagger process is already running');
  }

  const configPath = writeTempConfig(cfg);

  const args = [
    'ingest',
    '--config',
    configPath,
    '--source',
    opts.sourcePath,
    '--limit',
    String(opts.limit),
    '--concurrency',
    String(opts.concurrency ?? 4),
  ];
  if (opts.preview) {
    args.push('--preview');
  }

  const child = spawn(cfg.taggerBinPath, args, {
    env: {
      ...process.env,
      ANTHROPIC_API_KEY: opts.apiKey,
      // Force Rich to not use fancy formatting in piped output.
      NO_COLOR: '1',
      TERM: 'dumb',
      // Force Python's stdio to UTF-8 — the default on Windows is cp1252,
      // which can't encode characters rich uses in its output (e.g. `←`,
      // `✓`, en-dashes). Without this the tagger crashes with a
      // UnicodeEncodeError the first time it tries to print a success line.
      PYTHONIOENCODING: 'utf-8',
    },
    stdio: ['ignore', 'pipe', 'pipe'],
    windowsHide: true,
  });

  activeProcess = child;

  return new Promise<TaggerResult>((resolve) => {
    let stdoutBuf = '';
    let stderrBuf = '';

    child.stdout!.on('data', (chunk: Buffer) => {
      stdoutBuf += chunk.toString('utf-8');
      const lines = stdoutBuf.split('\n');
      // Keep the last (possibly incomplete) line in the buffer.
      stdoutBuf = lines.pop()!;
      for (const line of lines) {
        if (line.trim()) {
          console.log(`[tagger] ${line.trimEnd()}`);
          onProgress({ type: 'stdout', line: line.trimEnd() });
        }
      }
    });

    child.stderr!.on('data', (chunk: Buffer) => {
      stderrBuf += chunk.toString('utf-8');
      const lines = stderrBuf.split('\n');
      stderrBuf = lines.pop()!;
      for (const line of lines) {
        if (line.trim()) {
          console.warn(`[tagger] ${line.trimEnd()}`);
          onProgress({ type: 'stderr', line: line.trimEnd() });
        }
      }
    });

    child.on('close', (code, signal) => {
      // Flush any remaining partial lines.
      if (stdoutBuf.trim()) {
        onProgress({ type: 'stdout', line: stdoutBuf.trimEnd() });
      }
      if (stderrBuf.trim()) {
        onProgress({ type: 'stderr', line: stderrBuf.trimEnd() });
      }
      activeProcess = null;
      cleanupTempConfig(configPath);
      resolve({ exitCode: code, signal: signal ?? null });
    });

    child.on('error', (err) => {
      onProgress({ type: 'stderr', line: `Failed to start tagger: ${err.message}` });
      activeProcess = null;
      cleanupTempConfig(configPath);
      resolve({ exitCode: 1, signal: null });
    });
  });
}

/** Kill the currently running tagger process, if any. */
export function cancelTagger(): boolean {
  if (!activeProcess) return false;
  activeProcess.kill();
  return true;
}

/** Returns true if a tagger subprocess is currently running. */
export function isTaggerRunning(): boolean {
  return activeProcess !== null;
}
